### ISSUE TITLE
NNEDI3: #pragma optionNV(fastprecision on) causes issues on some GPUs

### ISSUE THREAD

**Issue by Shudouken** [bjin/mpv-prescalers#19]
I have a GeForce GTX 970 and those pragma lines seem to cause trouble for me.

raw.png
![raw](https://user-images.githubusercontent.com/1529740/30551077-deab0238-9c88-11e7-98dd-dda56e86d52a.png)

## nnedi3-nns32-win8x4.hook from master
```
mpv --no-config --window-scale=4 --vf=format=gray --opengl-shader=nnedi3-nns32-win8x4.hook --pause raw.png
```
![fastprecision_on](https://user-images.githubusercontent.com/1529740/30551120-006969e6-9c89-11e7-9b11-baac594907a0.png)

## nnedi3-nns32-win8x4.hook with all occurences of '#pragma optionNV(fastprecision on)' removed
```
mpv --no-config --window-scale=4 --vf=format=gray --opengl-shader=nnedi3-nns32-win8x4-nopragma.hook --pause raw.png
```
![fastprecision_off](https://user-images.githubusercontent.com/1529740/30551145-1169f724-9c89-11e7-84d3-25f692d31da4.png)

**Comment by bjin** [comment]
It's likely that low floating number precision optimization is applied to texture indexing coordinates as well, which could mess up the samplings completely. Ideally I would like the optimization applied only to NNEDI3 convolution kernels (which is in full single float precision without the pragma), but the `optionNV` pragma is a all-or-nothing deal.

Unfortunately with desktop OpenGL there is no working precision qualifier to specify precision for convolution kernels. A quick Google search shows that a recent OpenGL extension (`AMD_gpu_shader_half_float`) might be useful but it's AMD only ATM. 

For now I think I will just remove the optimization flag for nvidia card.

**Comment by haasn** [comment]
@bjin You could try making it a compute shader (even if you don't use shared memory, just add `//!COMPUTE 8 8` or so); that would then allow you to do the indexing calculations entirely with integers, texelFetch and gl_GlobalInvocationID

**Comment by bjin** [comment]
@haasn Good idea. (#11 for reference purpose).

**Comment by bjin** [comment]
Turns out compute shader doesn't solve the problem. To actually address the issue, one need to dump and read the GLSL assembly in nvidia's proprietary format, to understand which actually happened. Considering it's an obsolete optimization flag with limited docs, I think I'm fine without it.

**Comment by bjin** [comment]
Turns out that both `AMD_gpu_shader_half_float` and `NV_gpu_shader5` provides support of `float16_t`. There are also functions to pack and unpack two float from an int32 (`packFloat2x16` and `unpackFloat2x16`). On the other hand, there is also a standardized type qualifier `precise` from `ARB_gpu_shader5` which could help us workaround the texture coordinate issue, but it's less relevant compare to direct half float support.
