### ISSUE TITLE
More neurons?

### ISSUE THREAD

**Issue by kkkrackpot** [bjin/mpv-prescalers#2]
Hi!

Is it possible to make nnedi3 with more neurons, like 256 or 512?
Currently the script's `--nns` option accepts  max 128.

Regards,
Alex

**Comment by bjin** [comment]
`512 neurons` option is not available in the original implementation. On the other hand, I don't see it necessary to have `256 neurons` option either, considering the minimal (like placebo) improvement it brings and the huge size (around 700KB) and long compile time of the shader.

But yes, it's very straightforward to add this option. I don't have environment to test it at this moment though.

**Comment by bjin** [comment]
I added `nns=256` option in master, it's not tested though. I won't be surprised if some GLSL compiler failed to compile such large file.

Closing.

**Comment by kkkrackpot** [comment]
Thanks a lot!
