### ISSUE TITLE
README for precompiled shaders outdated?

### ISSUE THREAD

**Issue by kkkrackpot** [bjin/mpv-prescalers#21]
Hi,

Looks like NNEDI3 shaders have lost their suffixes (i.e. `-yuv`, `-chroma`, etc) and README is now outdated in this regard?

Is it still possible to use NNEDI3 upscaling for only, say, chroma planes?

Regards,
Alex

UPD. Didn't notice that RAVU still has suffixes. Sorry.

**Comment by bjin** [comment]
"chroma" and "yuv" profiles of NNEDI3 get removed because NNEDI3 is luma only, it's how model weights of NNEDI3 was trained. Please try "ravu-chroma", its quality is better and is much much faster.

Also, you can always get old shaders from an old commit. Those shaders are just not recommended now.

**Comment by kkkrackpot** [comment]
@bjin I will try RAVU, thanks.
What `-rX` number would you recommed?
Modern codecs (like h264 or HEVC) require `chroma-left` variant, right?

**Comment by bjin** [comment]
> What -rX number would you recommed?

The quality difference between `r3` and `r4` is minimal (you can verify this from the kernel visualization wiki page, most `r4` kernels have white weights(near zero) in their border). However, since `r4` is still very fast compare to nnedi3, it's what I would recommend.

> Modern codecs (like h264 or HEVC) require chroma-left variant, right?

Yes

**Comment by bjin** [comment]
> Please try "ravu-chroma", its quality is better and is much much faster.

I probably should clarify that, I mean quality of chroma upscaling.
