### ISSUE TITLE
nnedi3 picture shift

### ISSUE THREAD

**Issue by ghost** [bjin/mpv-prescalers#25]
Hello it seems that the current nnedi3 implementation shifts the image a little bit. Here's what I did:
* `mpv --no-config --screenshot-format=png --glsl-shaders=~/.config/mpv/shaders/nnedi3-nns16-win8x6.hook --start 00:02:02.455 my.mkv`
* Hit `s` and `^s`
* Scale the original one with vapoursynth.
* `convert -filter box -resize 400% -crop 800x800+0+0 +repage in.png out_crop.png` for both
* `convert -delay 30 *crop.png out.gif`
What I get:
![out](https://user-images.githubusercontent.com/8896798/32351541-065b1918-c01e-11e7-9824-c92ce8f5034d.gif)

PS: Oh yeah, I compared to a plain mpv lanczos upscale too (so vapoursynth isn't the bad one).

**Comment by bjin** [comment]
This is expected, both nnedi3 and RAVU shifts the picture by half pixel. Add `--no-scaler-resizes-only` to correct it.
