### ISSUE TITLE
ravu-lite: implement direct 3x and 4x prescaling

### ISSUE THREAD

**Issue by bjin** [bjin/mpv-prescalers#26]
RAVU could be trained to perform direct 3x and 4x prescaling, and is actually kind of straightforward in compute shader. As for fragment shader, there is a restriction that only 4 components can be stored in intermediate texture. Therefore, 2 passes is required to gather 8 components for 3x, and 4 passes is required to gather 16 components for 4x prescaling (assuming no offset). It might be the case that only compute shader implementation make sense in term of performance over repeated use of old 2x shader.

**Comment by realdevnullius** [comment]
Sorry for bumping! Is this what the ravu-3x-* shaders do? 3x prescaling and 4x prescaling? And by now you're not actively supporting the 4x prescaling?

And bonus newbie question if I may...? What's usually done by users after the prescaling is done? It's so hard to exactly see which shaders works on what and when that should be done and what should be followed. :)

Appreciated!

**Comment by bjin** [comment]
> Sorry for bumping! Is this what the ravu-3x-* shaders do? 3x prescaling and 4x prescaling? And by now you're not actively supporting the 4x prescaling?

You should probably use ravu-zoom now, which performs arbitrary ratio prescaling. 

> It's so hard to exactly see which shaders works on what and when that should be done and what should be followed. :)

You could probably check page 2 of stats (press `i` and then `2`), the rendering time of each passes.
