### ISSUE TITLE
Crash with >= nns32 versions of NNEDI3

### ISSUE THREAD

**Issue by grill02** [bjin/mpv-prescalers#30]
Hello, 
This might be related to https://github.com/bjin/mpv-prescalers/issues/6. But my platform is different (ubuntu trusty 14.04.5 LTS instead of OSX). I am using kernel 4.4.0-109-generic with amdgpu graphics driver  (radeon HD graphics)

I get a segmentation fault when using nnedi3 prescalers with nns greater than 32. I also get a crash with the 8x6 window scaler.
So these work:
nnedi3-nns16-win8x4.hook,nnedi3-nns16-win8x6.hook ,nnedi3-nns32-win8x4.hook
But all others crash.

I can chain the working prescalers ,for.eg
mpv --glsl-shaders="nnedi3-nns32-win8x4.hook:nnedi3-nns32-win8x4.hook" 
and it works great,but even one instance of a nns64 or nns 128 prescaler gives a segmentation fault. 

The gdb backtrace for  mpv --glsl-shaders="nnedi3-nns32-win8x6.hook" (the one for nns64 is similar) :

(gdb) bt
#0  0x00007fffd6b7a22b in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#1  0x00007fffd68cfdbc in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#2  0x00007fffd6ac275b in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#3  0x00007fffd6acf3aa in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#4  0x00007fffd6701355 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#5  0x00007fffd6702fb6 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#6  0x00007fffd67035d8 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#7  0x00007fffd66bc2af in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#8  0x00007fffd66f7be4 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#9  0x00007fffd670c96e in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#10 0x00007fffd6636a3a in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#11 0x0000000000559405 in link_shader (ra=0x7fffd038c370, ra=0x7fffd038c370, ok=0x7fffe4af4264, program=4) at ../video/out/opengl/ra_gl.c:735  [0/5571]
#12 compile_program (p=0x7fffe4af4320, ra=0x7fffd038c370) at ../video/out/opengl/ra_gl.c:767
#13 load_program (out_cached_data=<synthetic pointer>, p=0x7fffe4af4320, ra=0x7fffd038c370) at ../video/out/opengl/ra_gl.c:800
#14 gl_renderpass_create (ra=0x7fffd038c370, params=0x7fffe4af4320) at ../video/out/opengl/ra_gl.c:836
#15 0x0000000000546258 in create_pass (entry=0x7fffd0871ea0, sc=0x7fffd03d65f0) at ../video/out/gpu/shader_cache.c:627
#16 gl_sc_generate (sc=sc@entry=0x7fffd03d65f0, type=type@entry=RA_RENDERPASS_TYPE_RASTER, target_format=<optimized out>, vao=<optimized out>, 
    vao_len=vao_len@entry=2, vertex_stride=vertex_stride@entry=16) at ../video/out/gpu/shader_cache.c:948
#17 0x00000000005473d6 in gl_sc_dispatch_draw (sc=0x7fffd03d65f0, target=target@entry=0x7fffd0872370, vao=<optimized out>, vao_len=vao_len@entry=2, 
    vertex_stride=vertex_stride@entry=16, vertices=0x7fffd0469970, num_vertices=6) at ../video/out/gpu/shader_cache.c:984
#18 0x000000000054b14b in render_pass_quad (dst=0x7fffe4af4e40, fbo=..., p=0x7fffd03ee100) at ../video/out/gpu/video.c:1195
#19 finish_pass_fbo (p=p@entry=0x7fffd03ee100, fbo=..., dst=dst@entry=0x7fffe4af4e40) at ../video/out/gpu/video.c:1203
#20 0x000000000054da69 in finish_pass_tex (p=p@entry=0x7fffd03ee100, dst_tex=dst_tex@entry=0x7fffd0470950, w=w@entry=256, h=h@entry=144)
    at ../video/out/gpu/video.c:1232
#21 0x000000000054f6ad in pass_hook (p=p@entry=0x7fffd03ee100, name=0x1257041 "LUMA", img=..., trans=trans@entry=0x7fffe4af5260)
---Type <return> to continue, or q <return> to quit---
    at ../video/out/gpu/video.c:1446
#22 0x0000000000550d8f in pass_read_video (p=0x7fffd03ee100) at ../video/out/gpu/video.c:2031
#23 pass_render_frame (p=0x7fffd03ee100, mpi=<optimized out>, id=<optimized out>) at ../video/out/gpu/video.c:2685
#24 0x0000000000553351 in gl_video_render_frame (p=0x7fffd03ee100, frame=frame@entry=0x7fffd03e80b0, fbo=...) at ../video/out/gpu/video.c:3047
#25 0x0000000000564a55 in draw_frame (vo=0x226ec30, frame=0x7fffd03e80b0) at ../video/out/vo_gpu.c:88
#26 0x0000000000561ad1 in render_frame (vo=0x226ec30) at ../video/out/vo.c:866
#27 vo_thread (ptr=0x226ec30) at ../video/out/vo.c:970
#28 0x00007ffff54ac184 in start_thread (arg=0x7fffe4af6700) at pthread_create.c:312
#29 0x00007fffeeb94ffd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Some other system info

$$glxinfo |grep tring
server glx vendor string: SGI
server glx version string: 1.4
client glx vendor string: Mesa Project and SGI
client glx version string: 1.4
OpenGL vendor string: X.Org
OpenGL renderer string: Gallium 0.4 on AMD STONEY (DRM 3.1.0, LLVM 3.8.0)
OpenGL core profile version string: 4.1 (Core Profile) Mesa 11.2.0
OpenGL core profile shading language version string: 4.10
OpenGL version string: 3.0 Mesa 11.2.0
OpenGL shading language version string: 1.30

$$cat /var/log/Xorg.0.log|grep DRI
[    20.428] (**) AMDGPU(0): Option "DRI" "3"
[    21.232] (II) glamor: EGL version 1.4 (DRI2):
[    21.325] (II) AMDGPU(0): [DRI2] Setup complete
[    21.325] (II) AMDGPU(0): [DRI2]   DRI driver: radeonsi
[    21.325] (II) AMDGPU(0): [DRI2]   VDPAU driver: radeonsi
[    21.333] (**) AMDGPU(0): DRI3 enabled
[    21.804] (II) GLX: Initialized DRI2 GL provider for screen 0

$$lspci -nn |grep -E 'VGA|Display'
00:01.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Device [1002:98e4] (rev da)
01:00.0 Display controller [0380]: Advanced Micro Devices, Inc. [AMD/ATI] Sun XT [Radeon HD 8670A/8670M/8690M / R5 M330] [1002:6660] (rev ff)

$$mpv --version
mpv 386e8cd (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sun Nov 26 16:02:05 MMT 2017

btw, all other prescalers (ravi-r3/4,superxbr) work ok,even when chained together for 4x upscale. I cant use the compute shaders because of blue screen. Using the gather/ shaders does'nt give a significant improvement for me.

**Comment by bjin** [comment]
mostly likely a driver bug (unable to process shader with huge size), same as #6
