### ISSUE TITLE
using prescalers with vapoursynth scripts

### ISSUE THREAD

**Issue by grill02** [bjin/mpv-prescalers#31]
Hello
There is a vapoursynth version of nnedi3 (https://github.com/haasn/gentoo-conf/blob/xor/home/nand/.mpv/filters/nnedi3.vpy). On using one pass of that (even with nns 64 or 128), I get a 2x upscaled image. Can I chain the shader version of nnedi3 to this vapoursynth filter? 
The reason why this makes sense for me is that with the nnedi3 shader I can only use upto 32 neurons (I get a segmentation fault for higher numbers), but with the vapoursynth filter I can use upto 128 neurons easily as it runs on cpu. But 4x using vapoursynth is slower, so ideally I would like to first do a 2x upscale with vapoursynth (with 128 neurons) followed by a 2x upscale with the nnedi3 shader(with 32 neurons) so that I dont get framedrops. 

My question is, if I use a nnedi/ravu/superxbr prescaler with the vapoursynth filter, in what order does mpv apply the operations (i.e. first prescaler and then vapoursynth , or vice-versa). It seems less than optimal to first upscale with 32 neurons followed by a second upscale with 128 neurons ,since presumably the first upscale is more important and should correct for more edges.

If I use an mpv/vapoursynth filter (e.g. nnedi ,mirror, flip,smoothmotion etc) with scale=ewa_lanczossharp along with the prescaler, in what order will mpv apply these?
Will it be original_image->prescaler->filter->ewa_lanczossharp or original_image->prescaler->ewa_lanczossharp->filter. 

The reason why this matters to me is because I want to use smoothmotion(https://github.com/haasn/gentoo-conf/blob/xor/home/nand/.mpv/filters/mvtools.vpy) vapoursynth filter with my videos. But this filter works fastest on low-res and low-framerate videos. When I use prescalers with this filter, I get framedrops, but mpv works smoothly when this filter is used without prescalers.

When I use the vapoursynth nnedi3 filter, the video window doubles in size (for eg: a 424x240 window goes to 848x480) and the picture quality improves. When I use the nnedi( or superxbr/ravu) prescalers the image quality improves but the video window does'nt seem to change in size. So when I chain the smoothmotion vapoursynth filter with a prescaler, does the vapoursynth script get a 424x240 image or a 848x480 image?

**Comment by bjin** [comment]
Vapoursynth filter (in mpv )is how you preprocess video. OpenGl shader (in mpv) is how you present (processed) video to screen. They are independent to each other, totally unrelated.

There is no support of vapoursynth filters here
