### ISSUE TITLE
[REQUEST] Addition of CAS

### ISSUE THREAD

**Issue by Tsubajashi** [bjin/mpv-prescalers#36]
Hi!
i would like to know if its possible to get something like this: https://gist.github.com/martymcmodding/30304c4bffa6e2bd2eb59ff8bb09d135 inside mpv.
i tested it in games, and i overall like the way it looks.
im not able to port anything as i dont know much from that stuff.

[EDIT] thats the official page: https://gpuopen.com/gaming-product/fidelityfx/

**Comment by bjin** [comment]
pretty easy to port, assuming basic knowledge about GLSL and mpv hook shaders. I'm not interested to do so ATM though.
