### ISSUE TITLE
Release RAVU training code

### ISSUE THREAD

**Issue by haasn** [bjin/mpv-prescalers#37]
Would it be possible for you to release the RAVU training code so we can train our own set of weights on specific content we're interested in, rather than anime?

**Comment by bjin** [comment]
Check the [ravu branch](https://github.com/bjin/mpv-prescalers/tree/ravu).

Note that currently, `ravu` and `ravu-3x` are trained exclusively on anime. While `ravu-lite` and `ravu-zoom` are trained with the [DIV2K dataset](https://data.vision.ee.ethz.ch/cvl/DIV2K/).

**Comment by yeezylife** [comment]
> Would it be possible for you to release the RAVU training code so we can train our own set of weights on specific content we're interested in, rather than anime?

Does this means that I shouldn't use ruvu on real life Scenes?

**Comment by bjin** [comment]
> Does this means that I shouldn't use ruvu on real life Scenes?

use `ravu-lite`, it's much faster and trained on real life dataset.

**Comment by yeezylife** [comment]
> > Does this means that I shouldn't use ruvu on real life Scenes?
> > use `ravu-lite`, it's much faster and trained on real life dataset.

Thanks for replying. I'm currently using ruvu-zoom-r3. Does the zoom variants trained on real life dataset too?

**Comment by bjin** [comment]
> Does the zoom variants trained on real life dataset too?

Yes.
