### ISSUE TITLE
have standard glsl codes?

### ISSUE THREAD

**Issue by liuming15801** [bjin/mpv-prescalers#39]
hello, have standard glsl codes? no mpv glsl

**Comment by bjin** [comment]
"mpv glsl" IS standard glsl ultilizing mpv specific macro/function to access texture and mpv header annotation to manage shader invocation. These are neccesary and there is no universal solution for that.

If you are a developer who know a bit about OpenGL, it's actually pretty easy to port these shader to any OpenGL application.

If you are just a user, make sure your application actually actually support user shader and then make a feature request for that.

**Comment by liuming15801** [comment]
hi,  what's mean of "the texture that triggered this pass"?
thanks




hengfang.liu@tcl.com
 
From: bjin
Date: 2019-10-06 19:03
To: bjin/mpv-prescalers
CC: liuming15801; Author
Subject: Re: [bjin/mpv-prescalers] have standard glsl codes? (#39)
"mpv glsl" IS standard glsl ultilizing mpv specific macro/function to access texture and mpv header annotation to manage shader invocation. These are neccesary and there is no universal solution for that.
If you are a developer know a bit about OpenGL, it's actually pretty easy to port these shader to any OpenGL application.
If you are just a user, make sure your application actually actually support user shader and then make a feature request for that.
―

**Comment by bjin** [comment]
read the `HOOK` section of https://mpv.io/manual/master/#options-glsl-shaders
