### ISSUE TITLE
scale = bilinear (rgb) query

### ISSUE THREAD

**Issue by Shashank066** [bjin/mpv-prescalers#40]
@bjin  stats, I am seeing scale = bilinear (rgb) with ravu_zoom r4
Without ravu scale = ewa_lanczossharp (rgb) as specified in mpv.conf

![ravu zoom](https://user-images.githubusercontent.com/8770783/83322265-d2cfe480-a273-11ea-8a4a-b784cc5865c8.png)
![Without ravu](https://user-images.githubusercontent.com/8770783/83322271-d9f6f280-a273-11ea-93b5-e7f3fc15f6c8.png)

You had explained to another user:

> Chroma is upscaled to luma resolution (video size), and then the converted RGB is upscaled to target resolution (screen size).

Isn't bilinear a low quality algorithm for scaling? Is there a way to switch it to better algorithm or am I missing something?

```
glsl-shader = E:/Softwares/Video Player\mpv/shaders/KrigBilateral.glsl
glsl-shader = E:/Softwares/Video Player\mpv/shaders/SSimDownscaler.glsl
glsl-shader = E:/Softwares/Video Player\mpv/shaders/SSimSuperRes.glsl
glsl-shader = E:/Softwares/Video Player\mpv/shaders/ravu-zoom-r4.hook

scale = ewa_lanczossharp
cscale = ewa_lanczossharp
dscale = mitchell
correct-downscaling = yes

gpu-api = d3d11
hwdec = no
```

**Comment by deus0ww** [comment]
You're seeing scale=bilinear because the built-in scale is not actually used when ravu-zoom is active. This is controlled by the [scaler-resizes-only](https://mpv.io/manual/master/#options-scaler-resizes-only) option.

**Comment by Shashank066** [comment]
Thanks, that explains it.
