### ISSUE TITLE
Does ravu-zoom work with --cscale ?

### ISSUE THREAD

**Issue by hooke007** [bjin/mpv-prescalers#42]
I see that "ravu-zoom also comes with a chroma variant which is mostly a drop-in replacement of --cscale."
But I can see the --cscale in the stats' information. Does it real work or just the error display ?

![Snipaste_2021-01-10_15-31-23-tuya](https://user-images.githubusercontent.com/41094733/104117050-fe15c880-5358-11eb-960b-47da1e60da3a.jpg)

**Comment by Tsubajashi** [comment]
You only used the luma version. You specifically need the chroma version as well then.

**Comment by hooke007** [comment]
> You only used the luma version. You specifically need the chroma version as well then.

Thanks, maybe I misunderstood the MD.
