### ISSUE TITLE
RAVU LUTs in PNG format?

### ISSUE THREAD

**Issue by hizzlekizzle** [bjin/mpv-prescalers#43]
Hi, I was interested in trying to port RAVU to work with a program that needs LUTs in png format. Can you provide any guidance on generating/converting such a thing? Or would you happen to have them lying around? :)

**Comment by bjin** [comment]
I would recommend you porting ravu-lite, it's much simpler and has a relatively simple LUT table format. The LUT table is shuffled in generated shader, it's easier to use [raw model weights](https://github.com/bjin/mpv-prescalers/blob/source/weights/ravu-lite_weights-r3.py#L9) directly. It's a 5-dimension array, you can view code [here](https://github.com/bjin/mpv-prescalers/blob/source/ravu-lite.py#L81-L88) to understand the meaning for each dimension.

**Comment by hizzlekizzle** [comment]
Ah, ok. Yeah, we have a port of nnedi3 using the raw model weights, so I can probably approach it similarly. Thanks!
