### ISSUE TITLE
Why there isn't a Left/Center choice for "RAVU-Zoom-R2-Chroma.hook"?

### ISSUE THREAD

**Issue by yeezylife** [bjin/mpv-prescalers#44]
I'm afraid that I've chosen the wrong type of RAVU chroma upscale file..

These shaders are in my conf by the way:
` glsl-shaders              = "~~/shaders/ravu-zoom-r3.hook"`
` glsl-shaders-append  = "~~/shaders/ravu-zoom-r2-chroma.hook"`
` glsl-shaders-append  = "~~/shaders/SSimDownscaler.glsl"`
` glsl-shaders-append  = "~~/shaders/adaptive-sharpen.glsl"`

**Comment by bjin** [comment]
Those "left" "right" variant are outdated. The recent version of RAVU-Zoom can handle both chroma location with single shader file.

**Comment by yeezylife** [comment]
> Those "left" "right" variant are outdated. The recent version of RAVU-Zoom can handle both chroma location with single shader file.

Thanks for the clarification!
