### ISSUE TITLE
Broken alpha channel when using ravu-*-rgb on formats with alpha channels

### ISSUE THREAD

**Issue by haasn** [bjin/mpv-prescalers#45]
Using e.g. `ravu-r3-rgb` together with an RGBA source that has an alpha channel, RAVU currently produces very broken output. This is down to a combination of two issues:

1. RAVU always outputs the alpha channel as `0.0`, when it should really output something like `1.0` instead. This would be a marginal improvement over the status quo by making RAVU effectively perform alpha blending against black.

2. Even better would be to pass-through the alpha channel of, say, the center pixel, untouched. (Introduces slight drift but whatever, better than completely breaking alpha handling)

**Comment by hooke007** [comment]
ravu-*-yuv also broken in vo_gpu-next
