### ISSUE TITLE
Why was ravu-zoom-r4-chroma.hook removed?

### ISSUE THREAD

**Issue by zenwav** [bjin/mpv-prescalers#49]
Are there any specific reasons as to why it shouldn't be used? I seem to remember that it caused less power draw on my mobile GPU compared to the r3 version.

**Comment by bjin** [comment]
It's unlikely the case, r4 is much much slower than r3. r4 contains literally multiple times of instruments, and should be strictly slower. And I doubt it's able to run smoothly with a mobile GPU. Could you double check that r4 is rendered as expected on mobile GPU.

Anyhow, the reason r4 was removed (could still be generated from source branch) is that it gains so little considering it's even slower than some nnedi3 shader.
