### ISSUE TITLE
Is the prescale-luma replaced with opengl-shaders?

### ISSUE THREAD

**Issue by JulianLai** [bjin/mpv-prescalers#5]

**Comment by bjin** [comment]
Yes

**Comment by JulianLai** [comment]
@bjin There is `prescale-luma` in readme.md, if it is replaced with `opengl-shaders`, how to upscale with luma only?

**Comment by bjin** [comment]
Read [README](https://github.com/bjin/mpv-prescalers/blob/master/README.md).

TL;DR: Use files without any suffix, like `nnedi3-nns32-win8x4.hook`
