### ISSUE TITLE
How do I download these shaders.

### ISSUE THREAD

**Issue by Rubberxgum** [bjin/mpv-prescalers#50]
I'm still new to this and I don't know how to download the hook files from GitHub.

**Comment by bjin** [comment]
Click "Raw" button on the top right side of the page, after you open the `hook` file. And then, right click and save the file.

**Comment by hooke007** [comment]
![Snipaste_2022-07-24_10-18-59](https://user-images.githubusercontent.com/41094733/180640595-2d002980-fbdc-4069-a61e-2c2f7f3c2f75.jpg)
