### ISSUE TITLE
Any need for mpv's built-in antiringing when using new scalers?

### ISSUE THREAD

**Issue by Zabooby** [bjin/mpv-prescalers#55]
I've been using the following for ravu-lite-r4 and ravu-zoom-r3 (and basically all other external scalers I use) up till now:

```
scale-antiring=0.7
dscale-antiring=0.7
cscale-antiring=0.7
```

Is there any need for them now that the scalers already have an anti-ringing filters?

**Comment by bjin** [comment]
Those settings are for mpv builtin scalers, and won't effect user shaders like `ravu-lite`. You can keep those settings and use `ravu-lite-ar`, or remove those settings and use `ravu-zoom-ar` (since `ravu-zoom/ravu-zoom-rgb` replaces mpv builtin scaler)
