### ISSUE TITLE
Remove vulkan variants

### ISSUE THREAD

**Issue by haasn** [bjin/mpv-prescalers#58]
libplacebo has supported rgba16f on [vulkan since 2019](https://code.videolan.org/videolan/libplacebo/-/commit/cd1c305a68aac5ed49e8944f7106930187cdb67f), and on [d3d11 since jan 2023](https://code.videolan.org/videolan/libplacebo/-/commit/cd71614c22558de547dc76efaed9b9901eb62771). 'rgba16hf' shader variants are unnecessary

**Comment by bjin** [comment]
Thanks! I didn't notice these changes.

**Comment by haasn** [comment]
Incidentally, we can probably also remove need for `compute` variants by making CS support testable in conditions..

**Comment by bjin** [comment]
With my implementation `compute/` shaders are usually slower than `gather/` shaders for luma prescalers, but faster for `-rgb` prescalers. So probably not a good idea to prefer it blindly.

I was actually thinking about removing `gather/` shaders by testing `HOOKED_gather` macro defined by libplacebo, but it will introduce more a lot of complexity to shader code and I eventually give up this idea.
