### ISSUE TITLE
Crash with >= nns64 versions of NNEDI3

### ISSUE THREAD

**Issue by Argon-** [bjin/mpv-prescalers#6]
I wanted to test these shaders today and made my first try with `nnedi3-nns64-win8x4-yuv.hook` from your repo. The result was mpv crashing (segmentation fault) right at startup.
I remember I successfully tested your shaders some time ago so I checked the other files and while `nnedi3-nns64-win8x4.hook` seems to work, `nnedi3-nns64-win8x4-chroma.hook` and `nnedi3-nns64-win8x4-all.hook` result in crashes again.
One more test showed that all `nns32` variants work without crash, so maybe the problem is the shader's size? I know nothing about shaders, how could I confirm this? Is there something my GPU has to support for bigger shader files?

This is on OSX 10.11 running a AMD 6870 (a hackintosh) with support for OpenGL 4.1 (thanks Apple).
Not sure if useful but this is the stack trace I get:
    
    Thread 23 Crashed:: mpv/vo
    0   com.apple.AMDRadeonX3000GLDriver	0x0000000127645d53 0x1275d9000 + 445779
    1   com.apple.AMDRadeonX3000GLDriver	0x0000000127648248 0x1275d9000 + 455240
    2   com.apple.AMDRadeonX3000GLDriver	0x00000001276582f7 0x1275d9000 + 520951
    3   com.apple.AMDRadeonX3000GLDriver	0x000000012763b78f gldUpdateDispatch + 2853
    4   GLEngine                      	0x00007fff93fb3037 gleDoDrawDispatchCoreGL3 + 533
    5   GLEngine                      	0x00007fff93f637a8 gleDrawArraysOrElements_Entries_Body + 128
    6   GLEngine                      	0x00007fff93f5c632 glDrawArrays_GL3Exec + 173
    7   mpv                           	0x00000001093dd460 gl_vao_draw_data + 112
    8   mpv                           	0x00000001093e8353 finish_pass_direct + 1283
    9   mpv                           	0x00000001093e9c9d pass_hook + 2237
    10  mpv                           	0x00000001093e2d43 pass_render_frame + 2707
    11  mpv                           	0x00000001093e0cbc gl_video_render_frame + 1052
    12  mpv                           	0x00000001093f2307 draw_frame + 103
    13  mpv                           	0x00000001093ef346 vo_thread + 1030
    14  libsystem_pthread.dylib       	0x00007fff8288699d _pthread_body + 131
    15  libsystem_pthread.dylib       	0x00007fff8288691a _pthread_start + 168
    16  libsystem_pthread.dylib       	0x00007fff82884351 thread_start + 13

**Comment by bjin** [comment]
Based on the stacktrace, it's a driver bug.

Unfortunately, there is no obvious way to reduce the number of statements in shaders further. As a workaround, stick to nns=32 for now.

**Comment by Argon-** [comment]
Well, that's unfortunate.
Can I "safely" mix lower neuron chroma with higher neuron luma for comparisons or would the result be meaningless/skewed?

**Comment by bjin** [comment]
> Can I "safely" mix lower neuron chroma with higher neuron luma for comparisons or would the result be meaningless/skewed?

I don't know for sure, but I guess it can't go really bad if you think luma-only nnedi3 is nice-to-have. Those are quite subjective though.
