### ISSUE TITLE
Best upscaler to try?

### ISSUE THREAD

**Issue by arianaa30** [bjin/mpv-prescalers#60]
I just did some experiments with two of the upscaler shaders in MPV: ravu-lite-ar-r3.hook and ravu-r3.hook. But I didn't see any noticeable changes. Is it supposed to be like that or maybe I should try stronger shaders?

**Comment by Jules-A** [comment]
Are you sure the shaders are even being activated?

Also ravu-r3.hook is 5yrs old, you should try ravu-zoom-r3.hook (will always activate if you play content with resolutions smaller than the player's window size) or delete the shader's `when` conditions (for example ```//!WHEN HOOKED.w OUTPUT.w / 0.707106 < HOOKED.h OUTPUT.h / 0.707106 < *``` to make sure they activate.

Personally I use the gather version of ravu-zoom-ar-r3.hook

**Comment by arianaa30** [comment]
I invoked and ran it in `input.conf` just like other shaders (like Anime4K):
`CTRL+8 no-osd change-list glsl-shaders set "~~/shaders/ravu-r3.hook"; show-text "ravu-r3.hook: Mode 8 (HQ)"`

I will try the zoom one now.

**Comment by Jules-A** [comment]
> I invoked and ran it in `input.conf` just like other shaders (like Anime4K): `CTRL+8 no-osd change-list glsl-shaders set "~~/shaders/ravu-r3.hook"; show-text "ravu-r3.hook: Mode 8 (HQ)"`
> 
> I will try the zoom one now.

Even if you do that the shaders that you were trying to run won't run unless the content you are trying to play is bigger than the window's output resolution. For example if you have a 1440p monitor and try to activate it on a 4k video. You can check if it's activated by pressing Shift + i -> 2 .

ravu-zoom-ar-r3.hook for example should scale to your output resolution regardless unless I'm mistaken.

**Comment by bjin** [comment]
> Is it supposed to be like that or maybe I should try stronger shaders?

`ravu-lite-ar-r3` should bring much less artifacts compare to `ravu`. Make sure it's actually invoked from page 2 of stats page, as mentioned above. If you still can't notice the difference, you could probably just pick the one with less frame timing, or use built-in scalers if you wish.
