### ISSUE TITLE
Does RAVU have the same effect like NNEDI3 or super-xbr but lower resource hungry?

### ISSUE THREAD

**Issue by JulianLai** [bjin/mpv-prescalers#8]
Is it better than NNEDI3 or super-xbr?
Is there a lot difference between ravu-r2 and ravu-r3?

**Comment by bjin** [comment]
> Is it better than NNEDI3 or super-xbr?

They are not meant to be compared, RAVU is more like EWA scalers in general. it won't produce sharp upscaled image like nnedi3 and super-xbr, but it produces fewer artifacts like aliasing. It also seems to connect edges well. Anyway, I think it's not strictly better than either NNEID3 or superxbr.

> but lower resource hungry?

Yes, generally it should be comparable to EWA scalers performance-wise. There is still room for improvement, for example, by introducing compute shader.

> Is there a lot difference between ravu-r2 and ravu-r3?

You better perform the test yourself. The PSNR improvement is kind of significant, but I'm not sure how it's reflected visually. My guess is noticeable with still frame in selected area, but not with moving pictures.

**Comment by george-emerald** [comment]
For anyone wondering I compared ravu-lite-r4 to FSRCNNX_x2_16 and they produce almost identical images even though RAVU uses fewer than half of the resources. NNEDI3 with 32 neurons is slightly better and uses fewer resources than FSRCNNX.

**Comment by JohnChristianD** [comment]
> For anyone wondering I compared ravu-lite-r4 to FSRCNNX_x2_16 and they produce almost identical images even though RAVU uses fewer than half of the resources. NNEDI3 with 32 neurons is slightly better and uses fewer resources than FSRCNNX.

This is for anime, correct? There seems to be multiple seemingly independent sources corroborating nnedi is better even though https://artoriuz.github.io/blog/mpv_upscaling.html metrics suggests it's the least accurate upscaler. But then again, the choice of downscaler seems arbitrary and might change the rankings.

More importantly, does the ravu shaders only work on gpu-next? I get blue screens if I use them on gpu with the latest mpv installed by Chocolatey. (Didn't see it last time but found it in the description.)
Where's the archives for superxbr?
